# Generated by Namespacer - (https://github.com/Tattomoosa/o2)

const FuzzySearch := preload("uid://cgxjxp10xchrk")

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")

