# Generated by Namespacer - (https://github.com/Tattomoosa/o2)

const ArrayGroupHelper := preload("uid://s5mcd2si4sye")
const ColorMap := preload("uid://ctsu1j14g4d8p")
const IconGrabber := preload("uid://cfcfr654f5hq")
const Plugins := preload("uid://bww0iitok06k6")
const Settings := preload("uid://c03ir03eav5tv")
const SceneRootChangeNotifier := preload("uid://b6ngtrfs5mwos")

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")
